dist: bionic
language: php
php:
 - 8.2.17
cache:
 directories:
    - vendor
before_script:
 - composer install --prefer-dist --no-interaction --no-progress
script:
 - php artisan test
on:
 push:
    branches:
      - main
 pull_request:
    branches:
      - main
jobs:
 include:
    - stage: test
      script: php artisan test
